// <auto-generated />
using System;
using Justo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Justo.Migrations
{
    [DbContext(typeof(JustoDbContext))]
    partial class JustoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Justo-ADV")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Justo.Models.Advogado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Advogado_especialidade_Completo_Id")
                        .HasColumnType("int")
                        .HasColumnName("Advogado_especialidade_Completo_Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<string>("Oab")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar")
                        .HasColumnName("Oab");

                    b.Property<string>("Oab_UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar")
                        .HasColumnName("Oab_UF");

                    b.Property<int>("ProcessosId")
                        .HasColumnType("int")
                        .HasColumnName("ProcessosId");

                    b.Property<bool>("Status_Oab_Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Status_Oab_Ativo");

                    b.Property<int>("atualizadopor")
                        .HasColumnType("int")
                        .HasColumnName("atualizadopor");

                    b.Property<int>("cadastradopor")
                        .HasColumnType("int")
                        .HasColumnName("cadastradopor");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("dataatualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("datacadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cadastro");

                    b.HasKey("Id")
                        .HasName("PK_Advogados");

                    b.HasIndex("Advogado_especialidade_Completo_Id");

                    b.ToTable("Advogados", "Justo-ADV");
                });

            modelBuilder.Entity("Justo.Models.Advogado_especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Advogado_especialidade_completo_Id")
                        .HasColumnType("int")
                        .HasColumnName("Advogado_especialidade_completo_Id");

                    b.Property<string>("Nome_area_direito")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome_area_direito");

                    b.HasKey("Id")
                        .HasName("PK_Advogados_Especialidades");

                    b.ToTable("Advogados_Especialidades", "Justo-ADV");
                });

            modelBuilder.Entity("Justo.Models.Advogado_especialidade_completo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvogadoId")
                        .HasColumnType("int")
                        .HasColumnName("AdvogadoId");

                    b.Property<int>("Advogado_especialidade_Id")
                        .HasColumnType("int")
                        .HasColumnName("Advogado_especialidade_Id");

                    b.Property<string>("Cpf_especialidade_completo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("Cpf_especialidade_completo");

                    b.Property<string>("Nome_advogado_completo")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome_advogado_completo");

                    b.Property<string>("Nome_especialidade_completo")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome_especialidade_completo");

                    b.Property<string>("Oab_especialidade_completo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar")
                        .HasColumnName("Oab_especialidade_completo");

                    b.Property<string>("Oab_uf_especialidade_completo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar")
                        .HasColumnName("Oab_uf_especialidade_completo");

                    b.Property<bool>("Status_Oab_Ativo_completo")
                        .HasColumnType("bit")
                        .HasColumnName("Status_Oab_Ativo_completo");

                    b.Property<int>("atualizadopor")
                        .HasColumnType("int")
                        .HasColumnName("atualizadopor");

                    b.Property<int>("cadastradopor")
                        .HasColumnType("int")
                        .HasColumnName("cadastradopor");

                    b.Property<DateTime>("dataatualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("datacadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cadastro");

                    b.HasKey("Id")
                        .HasName("PK_Advogados_Especialidades_Completos");

                    b.HasIndex("AdvogadoId");

                    b.HasIndex("Advogado_especialidade_Id");

                    b.ToTable("Advogados_Especialidades_Completos", "Justo-ADV");
                });

            modelBuilder.Entity("Justo.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia_bancaria_cliente")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Agencia_bancaria_cliente");

                    b.Property<string>("Banco_cliente")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Banco_cliente");

                    b.Property<string>("Certificado_reservista_cliente")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("Certificado_reservista_cliente");

                    b.Property<string>("Cnh_cliente")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Cnh_cliente");

                    b.Property<string>("Cnpj_cliente")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("Cnpj_cliente");

                    b.Property<string>("Contato_de_confianca_cliente")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Contato_de_confianca_cliente");

                    b.Property<string>("Contrato_social_cliente")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Contrato_social_cliente");

                    b.Property<string>("Cpf_cliente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("Cpf_cliente");

                    b.Property<DateTime>("Data_nascimento_cliente")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_nascimento_cliente");

                    b.Property<string>("Email_cliente")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Email_cliente");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado_civil_cliente")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Estado_civil_cliente");

                    b.Property<string>("Genero_cliente")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar")
                        .HasColumnName("Genero_cliente");

                    b.Property<string>("Nacionalidade_cliente")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Nacionalidade_cliente");

                    b.Property<string>("Nome_cliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome_cliente");

                    b.Property<string>("Ocupacao_cliente")
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Ocupacao_cliente");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Procuracao_representacao_legal_cliente")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("Procuracao_representacao_legal_cliente");

                    b.Property<string>("Rg_cliente")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar")
                        .HasColumnName("Rg_cliente");

                    b.Property<string>("Telefone_cliente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("Telefone_cliente");

                    b.Property<string>("Tipo_cliente")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar")
                        .HasColumnName("Tipo_cliente");

                    b.Property<int>("atualizadopor")
                        .HasColumnType("int")
                        .HasColumnName("atualizadopor");

                    b.Property<int>("cadastradopor")
                        .HasColumnType("int")
                        .HasColumnName("cadastradopor");

                    b.Property<DateTime>("dataatualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("datacadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cadastro");

                    b.HasKey("Id")
                        .HasName("PK_Clientes");

                    b.ToTable("Clientes", "Justo-ADV");
                });

            modelBuilder.Entity("Justo.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("atualizadopor")
                        .HasColumnType("int");

                    b.Property<int>("cadastradopor")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataatualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("datacadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cadastro");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Endereco", "Justo-ADV");
                });

            modelBuilder.Entity("Justo.Models.Site_contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Analisado_contato")
                        .HasColumnType("bit")
                        .HasColumnName("Analisado_contato");

                    b.Property<string>("Assunto_contato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Assunto_contato");

                    b.Property<string>("Conteudo_contato")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar")
                        .HasColumnName("Conteudo_contato");

                    b.Property<string>("Email_contato")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Email_contato");

                    b.Property<string>("Nome_contato")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome_contato");

                    b.Property<string>("Telefone_contato")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("Telefone_contato");

                    b.Property<string>("Tipo_causa_contato")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar")
                        .HasColumnName("Tipo_causa_contato");

                    b.Property<bool>("Virar_cliente_contato")
                        .HasColumnType("bit")
                        .HasColumnName("Virar_cliente_contato");

                    b.Property<int>("atualizadopor")
                        .HasColumnType("int")
                        .HasColumnName("atualizadopor");

                    b.Property<int>("cadastradopor")
                        .HasColumnType("int")
                        .HasColumnName("cadastradopor");

                    b.Property<DateTime>("dataatualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("datacadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cadastro");

                    b.HasKey("Id")
                        .HasName("PK_Site_contato");

                    b.ToTable("Site_contato", "Justo-ADV");
                });

            modelBuilder.Entity("Justo.Models.Advogado", b =>
                {
                    b.HasOne("Justo.Models.Advogado_especialidade_completo", null)
                        .WithMany("Advogados")
                        .HasForeignKey("Advogado_especialidade_Completo_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Justo.Models.Advogado_especialidade_completo", b =>
                {
                    b.HasOne("Justo.Models.Advogado", null)
                        .WithMany("Advogados_Especialidades_Completos_ADV")
                        .HasForeignKey("AdvogadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Justo.Models.Advogado_especialidade", "Advogado_Especialidades")
                        .WithMany("Advogados_Especialidades_Completos_ESPEC")
                        .HasForeignKey("Advogado_especialidade_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advogado_Especialidades");
                });

            modelBuilder.Entity("Justo.Models.Endereco", b =>
                {
                    b.HasOne("Justo.Models.Clientes", null)
                        .WithOne("Endereco_cliente")
                        .HasForeignKey("Justo.Models.Endereco", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Justo.Models.Advogado", b =>
                {
                    b.Navigation("Advogados_Especialidades_Completos_ADV");
                });

            modelBuilder.Entity("Justo.Models.Advogado_especialidade", b =>
                {
                    b.Navigation("Advogados_Especialidades_Completos_ESPEC");
                });

            modelBuilder.Entity("Justo.Models.Advogado_especialidade_completo", b =>
                {
                    b.Navigation("Advogados");
                });

            modelBuilder.Entity("Justo.Models.Clientes", b =>
                {
                    b.Navigation("Endereco_cliente")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
